### ISSUE TITLE
[API] Workshop: [July] [17]-[18], [2023]

### ISSUE THREAD

**Issue by RinatS** [im-customers/axciom#2]
Add the contact info below:

- First Name/Last Name
- Business email address
- Role in customer org

**Comment by RinatS** [comment]
Rinat Shagisultanov
Tech Director
rinats@infomagnus.com

**Comment by avinp-git** [comment]
Avinash Pandey
Data Architect
avinash.pandey@acxiom.com

**Comment by acx-kesand** [comment]
Ken Sanders
Application Engineer - GH Enterprise Admin
kenneth.sanders@acxiom.com

**Comment by piotif83** [comment]
Piotr Formela
Solutions Developer
piotr.formela@acxiom.com

**Comment by MonikaDuch** [comment]
Monika Duchnowska
Manager Delivery/Solution Developer
monika.duchnowska@acxiom.com

**Comment by tonycwang** [comment]
Tony Wang
Sr. Solutions Developer
tony.wang@acxiom.com

**Comment by RinatS** [comment]
Recordings

Day 1: https://infomagnus365-my.sharepoint.com/:v:/g/personal/rinat_shagisultanov_infomagnus_com/ETojJwJroeBFgag4WHR0fyEBr_7nSNDpIyZfMA_vVCC1Dw?e=Mx63s5

Day 2: https://infomagnus365-my.sharepoint.com/:v:/g/personal/rinat_shagisultanov_infomagnus_com/EfwUrlMvye9HuLgXd0rgxqMBhRgkGrnlXDJXm-mia0RUPg?e=HTpI1g

**Comment by RinatS** [comment]
Slide deck: https://github.com/im-customers/github-api-training
